class Daemons:
  def __init__(self):
    self.Bael
    self.Agares
    self.Vassago
    self.Samigina
    self.Marbas
    self.Valefor
    self.Amon
    self.Barbatos
    self.Paimon
    self.Buer
    self.Gusion
    self.Sitri
    self.Beleth
    self.Leraje
    self.Eligos
    self.Zepar
    self.Botis
    self.Bathin
    self.Sallos
    self.Purson
    self.Morax
    self.Ipos
    self.Aim
    self.Naberius
    self.GlasyaLabolas
    self.Bune
    self.Ronove
    self.Berith
    self.Astaroth
    self.Forneus
    self.Foras
    self.Asmodai
    self.Gaap
    self.Furfur
    self.Marchosias
    self.Stolas
    self.Phenex
    self.Halphas
    self.Malphas
    self.Raum
    self.Focalor
    self.Vepar
    self.Sabnock
    self.Shan
    self.Vine
    self.Bifrons
    self.Uvall
    self.Haagenti
    self.Crocell
    self.Furcas
    self.Balam
    self.Alloces
    self.Camio
    self.Murmur
    self.Orobas
    self.Gremory
    self.Oso
    self.Amy
    self.Orias
    self.Vapula
    self.Zagan
    self.Volac
    self.Andras
    self.Haures
    self.Andrealphus
    self.Cimejes
    self.Amdusias
    self.Belial
    self.Decarbia
    self.Seere
    self.Dantalion
    self.Andromalius
  }
